packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.6
  react-dom: ^19.2.6
  i18next: ^26.3.0
  react-i18next: ^17.0.0
  i18next-parser: ^9.4.0
  typescript: ~6

allowBuilds:
  esbuild: true
  msw: false
